"""
IF Source Base Module - Abstract Interface for IQ Signal Sources
================================================================

This module provides the abstract base class for controlling IF (Intermediate Frequency)
sources that generate IQ signals for RF applications. These sources typically have two
outputs (I and Q) that are upconverted using an IQ mixer and Local Oscillator (LO).

Key Features:
-------------
- Support for multi-frequency signal generation (multiple tones simultaneously)
- IQ imbalance correction using calibration parameters (g, phi)
- DC offset correction for I and Q channels
- Automatic calibration file loading and parameter interpolation
- High-level interface that abstracts calibration complexity

Calibration System:
------------------
To achieve single-sideband upconversion without unwanted mirror frequencies, the system
requires calibration for each combination of:
- IF frequency (the frequency generated by this source)
- LO frequency (the local oscillator frequency used for upconversion)
- IF amplitude (the signal amplitude)

Calibration parameters:
- g: Gain imbalance between I and Q channels
- phi: Phase imbalance from ideal 90° quadrature
- I_offset: DC offset for I channel (V)
- Q_offset: DC offset for Q channel (V)

Multi-Frequency Support:
-----------------------
The system can generate multiple frequency components simultaneously. Each frequency
component has its own calibration parameters (g, phi), but DC offsets are physical
properties of the output channels, so they are averaged across all active frequencies.

Usage Example:
-------------
```python
# Create source instance (concrete implementation)
source = ConcreteIFSource("device_address")
source.connect()

# Single frequency with manual calibration
config = IQDeviceConfig(
    components=[IQComponentConfig(frequency=21.58e6, amplitude=0.5)],
    dc_offset_i=0.001,
    dc_offset_q=-0.002
)
source.configure_signal(config)

# Multi-frequency with automatic calibration
frequencies = [19.422e6, 21.580e6, 23.738e6]  # Hz
amplitudes = [0.3, 0.4, 0.3]  # normalized 0-1
lo_frequency = 2.6e9  # Hz

# Calibration files should contain columns:
# lo_frequency_ghz, if_amplitude, g, phi, I_offset, Q_offset
# Optional: sideband ('upper'/'lower') for sanity checks
calibration_files = {
    19.422e6: "calibration_IF_19.422MHz.csv",
    21.580e6: "calibration_IF_21.580MHz.csv",
    23.738e6: "calibration_IF_23.738MHz.csv"
}

source.set_multi_frequency_signal(frequencies, amplitudes, lo_frequency, calibration_files)
source.enable_output(True)
```

Classes:
--------
- IQComponentConfig: Configuration for a single frequency component
- IQDeviceConfig: Complete device configuration with multiple components
- IFSourceBase: Abstract base class for IF sources

"""

# if_source_base.py
from abc import ABC, abstractmethod
import logging
from typing import Tuple, Optional, Dict, List, Union
from dataclasses import dataclass
import pandas as pd
import numpy as np


@dataclass
class IQComponentConfig:
    """Configuration for a single IQ signal component."""
    frequency: float  # Hz
    amplitude: float  # 0-1 for normalized amplitude
    amplitude_i: float = None  # Corrected I amplitude (calculated)
    amplitude_q: float = None  # Corrected Q amplitude (calculated)
    phase_i: float = 0.0  # degrees
    phase_q: float = 270.0  # degrees (default: USB operation)
    enabled: bool = True
    # FM parameters
    fm_enabled: bool = False
    fm_deviation_khz: float = 0.0  # kHz

    def __post_init__(self):
        # If corrected amplitudes not set, use base amplitude
        if self.amplitude_i is None:
            self.amplitude_i = self.amplitude
        if self.amplitude_q is None:
            self.amplitude_q = self.amplitude


@dataclass
class IQDeviceConfig:
    """Configuration for IQ signal generation with multiple components."""
    components: List[IQComponentConfig]
    dc_offset_i: float = 0.0  # V
    dc_offset_q: float = 0.0  # V
    fm_modulation_frequency: Optional[float] = None  # Hz - shared for all components
    iq_phase_offset: Optional[float] = None  # degrees - IQ demodulation phase offset

    @property
    def num_components(self) -> int:
        return len(self.components)

    @property
    def active_components(self) -> List[IQComponentConfig]:
        return [c for c in self.components if c.enabled]


class IFSourceBase(ABC):
    """Abstract base class for IF signal sources supporting multi-frequency generation with FM."""

    def __init__(self, name: str = "IF Source"):
        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")
        self.name = name
        self._is_connected = False
        self._current_config = None
        self._calibration_data = {}  # Dict mapping frequency to calibration DataFrame
        self._max_components = 1  # Default, subclasses can override
        self._sideband = "upper"

    @staticmethod
    def _normalize_sideband(sideband: str) -> str:
        sideband_normalized = str(sideband).strip().lower()
        if sideband_normalized in {"upper", "usb"}:
            return "upper"
        if sideband_normalized in {"lower", "lsb"}:
            return "lower"
        raise ValueError(f'Invalid sideband "{sideband}". Use "upper"/"usb" or "lower"/"lsb".')

    @property
    def sideband(self) -> str:
        return self._sideband

    def set_sideband(self, sideband: str) -> None:
        self._sideband = self._normalize_sideband(sideband)
        self.logger.info(f"Sideband set to {self._sideband.upper()}")

    def _q_base_phase_deg(self) -> float:
        return 270.0 if self._sideband == "upper" else 90.0

    @property
    def max_components(self) -> int:
        """Maximum number of frequency components supported."""
        return self._max_components

    @abstractmethod
    def connect(self, **kwargs) -> None:
        """Connect to the IF source."""
        pass

    @abstractmethod
    def disconnect(self) -> None:
        """Disconnect from the IF source."""
        pass

    @abstractmethod
    def configure_signal(self, config: IQDeviceConfig) -> None:
        """Configure the IQ signal parameters for all components."""
        pass

    @abstractmethod
    def configure_component(self, component_index: int, config: IQComponentConfig) -> None:
        """Configure a single frequency component."""
        pass

    @abstractmethod
    def enable_output(self, enable: bool = True) -> None:
        """Enable or disable the output."""
        pass

    @abstractmethod
    def set_dc_offsets(self, i_offset: float, q_offset: float) -> None:
        """Set DC offsets for I and Q channels."""
        pass

    @abstractmethod
    def set_iq_correction(self, component_index: int, if_amplitude: float,
                          gain_imbalance: float, phase_imbalance: float) -> Tuple[float, float, float, float]:
        """
        Apply IQ imbalance correction for a specific component.

        Parameters:
        -----------
        component_index : int
            Index of the frequency component (0 to max_components-1)
        if_amplitude : float
            IF signal amplitude (0 to 1)
        gain_imbalance : float
            Gain imbalance parameter (g)
        phase_imbalance : float
            Phase imbalance parameter (phi) in radians

        Returns:
        --------
        tuple : (amplitude_i, amplitude_q, phase_i, phase_q)
        """
        pass

    @abstractmethod
    def load_calibration_data(self, frequency: float, path: str) -> pd.DataFrame:
        """
        Load IQ calibration settings for a specific frequency from a CSV file.

        Parameters:
        -----------
        frequency : float
            IF frequency in Hz
        path : str
            Path to the calibration CSV file

        Returns:
        --------
        pd.DataFrame : Loaded calibration data
        """
        pass

    def set_fm_modulation_frequency(self, frequency: float) -> None:
        """
        Set the FM modulation frequency (shared for all components).

        Parameters:
        -----------
        frequency : float
            FM modulation frequency in Hz
        """
        raise NotImplementedError("FM modulation not supported by this device")

    def set_multi_frequency_signal(self, frequencies: List[float], amplitudes: List[float],
                                   lo_frequency: float, calibration_files: Optional[Dict[float, str]] = None,
                                   fm_enables: Optional[Union[bool, List[bool]]] = None,
                                   fm_deviations_khz: Optional[Union[float, List[float]]] = None,
                                   fm_modulation_frequency: Optional[float] = None) -> None:
        """
        Convenience method to set up a multi-frequency signal with automatic calibration and FM support.

        Parameters:
        -----------
        frequencies : List[float]
            List of IF frequencies in Hz
        amplitudes : List[float]
            List of amplitudes (0 to 1) for each frequency
        lo_frequency : float
            LO frequency in Hz
        calibration_files : Optional[Dict[float, str]]
            Dictionary mapping frequency to calibration file path.
            If None, will look for default files based on frequency.
        fm_enables : Optional[Union[bool, List[bool]]]
            Enable FM for each component. If single bool, applies to all.
        fm_deviations_khz : Optional[Union[float, List[float]]]
            FM deviation in kHz for each component. If single float, applies to all.
        fm_modulation_frequency : Optional[float]
            FM modulation frequency in Hz (shared for all components)
        """
        if len(frequencies) != len(amplitudes):
            raise ValueError("Frequencies and amplitudes lists must have the same length")

        if len(frequencies) > self.max_components:
            raise ValueError(f"Too many frequencies. Maximum supported: {self.max_components}")

        # Process FM parameters
        if fm_enables is not None:
            if isinstance(fm_enables, bool):
                fm_enables = [fm_enables] * len(frequencies)
            elif len(fm_enables) != len(frequencies):
                raise ValueError("fm_enables list must match frequencies length")
        else:
            fm_enables = [False] * len(frequencies)

        if fm_deviations_khz is not None:
            if isinstance(fm_deviations_khz, (int, float)):
                fm_deviations_khz = [float(fm_deviations_khz)] * len(frequencies)
            elif len(fm_deviations_khz) != len(frequencies):
                raise ValueError("fm_deviations_khz list must match frequencies length")
        else:
            fm_deviations_khz = [0.0] * len(frequencies)

        # Load calibration data for each frequency if not already loaded
        #
        # Behaviour:
        # - If `calibration_files` is None: try the default filename for missing calibrations.
        # - If `calibration_files` is a dict (even empty): only try to load files explicitly
        #   provided for a given IF frequency.
        for freq in frequencies:
            if freq in self._calibration_data:
                continue

            cal_file = None
            if calibration_files is None:
                cal_file = f'calibration_redpitaya_all_results_IF_{freq / 1e6:.3f}MHz.csv'
            elif freq in calibration_files:
                cal_file = calibration_files[freq]

            if not cal_file:
                continue

            try:
                self.load_calibration_data(freq, cal_file)
            except Exception as e:
                self.logger.warning(
                    f"Could not load calibration for {freq / 1e6:.3f} MHz: {e}"
                )

        # Create component configurations
        components = []
        dc_offsets_i = []
        dc_offsets_q = []

        for i, (freq, amp, fm_enable, fm_dev) in enumerate(zip(frequencies, amplitudes, fm_enables, fm_deviations_khz)):
            component = IQComponentConfig(
                frequency=freq,
                amplitude=amp,
                fm_enabled=fm_enable,
                fm_deviation_khz=fm_dev
            )

            # Default quadrature phases based on desired sideband.
            component.phase_i = 0.0
            component.phase_q = self._q_base_phase_deg()

            # Apply calibration if available
            if freq in self._calibration_data:
                try:
                    g, phi, i_offset, q_offset = self._interpolate_calibration_parameters(
                        freq, lo_frequency / 1e9, amp
                    )

                    # Calculate corrected amplitudes and phases
                    component.amplitude_i = amp * (1 + g)
                    component.amplitude_q = amp * (1 - g)
                    component.phase_i = 0.0
                    component.phase_q = float((self._q_base_phase_deg() + np.degrees(phi)) % 360.0)

                    dc_offsets_i.append(i_offset)
                    dc_offsets_q.append(q_offset)

                except Exception as e:
                    self.logger.warning(f"Could not apply calibration for {freq / 1e6:.3f} MHz: {e}")

            components.append(component)

        # Calculate average DC offsets
        avg_dc_offset_i = np.mean(dc_offsets_i) if dc_offsets_i else 0.0
        avg_dc_offset_q = np.mean(dc_offsets_q) if dc_offsets_q else 0.0

        # Create and apply configuration
        config = IQDeviceConfig(
            components=components,
            dc_offset_i=avg_dc_offset_i,
            dc_offset_q=avg_dc_offset_q,
            fm_modulation_frequency=fm_modulation_frequency
        )

        self.configure_signal(config)

        # Set FM modulation frequency if supported
        if fm_modulation_frequency is not None and any(fm_enables):
            try:
                self.set_fm_modulation_frequency(fm_modulation_frequency)
            except NotImplementedError:
                self.logger.warning("FM modulation not supported by this device")

        self.logger.info(f"Configured {len(components)} frequency components with calibration")
        if any(fm_enables):
            self.logger.info(
                f"FM enabled on {sum(fm_enables)} components with modulation frequency {fm_modulation_frequency / 1e3:.3f} kHz")

    @abstractmethod
    def _interpolate_calibration_parameters(self, frequency: float, lo_frequency_ghz: float,
                                            if_amplitude: float) -> Tuple[float, float, float, float]:
        """
        Interpolate calibration parameters for a given frequency and amplitude.

        Parameters:
        -----------
        frequency : float
            IF frequency in Hz
        lo_frequency_ghz : float
            LO frequency in GHz
        if_amplitude : float
            IF amplitude (0 to 1)

        Returns:
        --------
        tuple : (g, phi, i_offset, q_offset)
        """
        pass

    def get_current_config(self) -> Optional[IQDeviceConfig]:
        """Get the current signal configuration."""
        return self._current_config

    @property
    def is_connected(self) -> bool:
        """Check if the source is connected."""
        return self._is_connected

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        if self.is_connected:
            self.disconnect()

    def __repr__(self) -> str:
        """String representation."""
        return f"{self.__class__.__name__}(name='{self.name}', connected={self.is_connected})"
